[project]
name = "captcha-reader-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "pillow>=12.3.0",
    "scikit-learn>=1.9.0",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
    "tqdm>=4.70.0",
]
